### ISSUE TITLE
Wierd

### ISSUE THREAD

**Issue by ErrorC0de5** [Gopro336/Muffin-SRC-BUILDABLE#2]
Client works for a few seconds then forces you into the void whcih you cannot get out of. Have no idea what the fuck is wrong with it

**Comment by ErrorC0de5** [comment]
Nvr mind its the combat mode module you gotta turn all the settings off in that

**Comment by Gopro336** [comment]
ok

**Comment by Gopro336** [comment]
I will work on a solution to that bug when I have time

**Comment by TwoThreeTwo** [comment]
Some Combat Module found in Other, I messed around with its settings and it worked. I dont rlly know which worked but just try

**Comment by TwoThreeTwo** [comment]
combatStatus*
